### ISSUE TITLE
Error message: Access denied (-17)

### ISSUE THREAD

**Issue by sunhater** [vanssata/Borica_3DS#5]
Привет,
Поздравления за готовия скрипт. Моля за съвет как да го подкарам.
Правя всичко както е написано в тестов режим, излизат ми NONCE и P_SIGN. Когато умишлено сбъркам частния RSA ключ, P_SIGN e празно. Но и в двата случая отговора от сървъра е един и същ:

`https://3dsgate-dev.borica.bg/cgi-bin/cgi_link`
Sorry, due to technical fault your request cannot be processed (3)
Error message: Access denied (-17)
Please try once again or visit us later or choose another means of payment.

Погледнах че кода за грешка -17 означава "Грешка при проверка на P_SIGN", което ме навежда на мисълта, че има проблем при изчисляването на P_SIGN. Това, което съм направил преди да тествам е:

- Попълних `$terminal_id` с номера на терминала.

- Попълних `$merchant_test_private_key` със съдържанието на `{tid}_{date}_D.key` файла който първоначално се създава.

- Попълних `$borica_test_public_key` със съдържанието на `{tid}-{domain}-D.pub` файла, който ми беше предоставен от банката.

- Промених `$test_return_url`

- В метода `generateBoricaRequestFieldsForTRTYPE_1()` промених полето EMAIL.

Моля ако имате някакви идеи за това какво не е направено както трябва, да отговорите

**Comment by vanssata** [comment]
Здравейте. обикчновено тази грешка идва при сгрешени ключове. 
Така от вторник има нова имплементация при която в подписа на P_SING се изисква още едно поле. 
Това трябва да е опоменато в документацията. 


Внимавайте дали няма passphrase на ключовете, другото за което трябва да се внимава е версията на PHP скрипта е тестван и работи на 5.6+ до 7.3 включително за 7.4 и нагоре все още не е тестван. 

През почивните дни ще пусна update на скрипта, с новите изисквания и разяснения.

**Comment by nstoichkov7** [comment]
Здравейте,
Първо искам да Ви благодаря за имплеметацията мисля че ще е от полза на много хора 

По темата забелязах че фукнцията generate_signature_message_from_TRYTIPE_1 в момента  ползва  полетата MAC_COMMON които са:  TERMINAL, TRTYPE, AMOUNT, TIMESTAMP

Както автора е написал има нови полета от скоро. 
При мен работи като подам полетата от MAC_EXTENDED а те са:  ACTION, RC, APPROVAL, TERMINAL, TRTYPE, AMOUNT, CURRENCY, ORDER, RRN, INT_REF, PARES_STATUS, ECI, TIMESTAMP,NONCE

**Comment by dimitarminchev** [comment]
Здавейте, действително още не е имплементирано MAC_EXTENDED. 

PHP примери по версия 2.2 на документацита  можете да видите тук [Borica Request 2.2](https://gist.github.com/dimitarminchev/08d8ab833fa481a8cc5c1e365a16c05e) и [Borica Responce 2.2](https://gist.github.com/dimitarminchev/34265c2c780ccff86a545eb4a1ffd88c). 

Дайте по един лайк ако Ви харесват :)

**Comment by nstoichkov7** [comment]
> Здавейте, действително още не е имплементирано MAC_EXTENDED.
> 
> PHP примери по версия 2.2 на документацита можете да видите тук [Borica Request 2.2](https://gist.github.com/dimitarminchev/08d8ab833fa481a8cc5c1e365a16c05e) и [Borica Responce 2.2](https://gist.github.com/dimitarminchev/34265c2c780ccff86a545eb4a1ffd88c).
> 
> Дайте по един лайк ако Ви харесват :)

Здравейте, 
Още снощи като ги намерих им дадох по една звезда, орпеделно са позлезни браво че сте ги качили.
Отностно Borica Responce 2.2 имам един въпрос задал съм го в коментарите под него

**Comment by veronika793** [comment]
Здравейте,
Полезни скриптове, но стигам и аз до същия резултат дори и с ъпдейтнатите скриптове Borica Request 2.2 и MAC_EXTENDED полетата за генериране на P_SIGN. 
RC CODE: -17
ACTION: 3

![image](https://user-images.githubusercontent.com/7135591/97485735-2baac280-1963-11eb-964e-ea13fdcf4cd0.png)

Скриптовете пускам през docker като естествено сменям private key-a, terminal, merchant, callback url-a води към дев средите с инсталиран сертификат и pub key даден от борика. В момента използвайки php скрипта след бутон продължи ме връща директно на callback-a със статус кодовете описани по-горе.

Възможно ли е да изпускам нещо или php скриптовете евентуално да имат нужда от някаква доработка  :/?

**Comment by sunhater** [comment]
Благодаря за отговорите. Успях с [другия код](https://gist.github.com/dimitarminchev/08d8ab833fa481a8cc5c1e365a16c05e). Все пак си направих и аз готова библиотека [тук](https://github.com/sunhater/shBorica) която пасва на моите нужди. Все още няма документация, но мисля всеки ще се оправи.
